apiVersion: batch/v1
kind: CronJob
metadata:
  name: trust-score-check
  labels:
    app: self-healing
    owner: prasanna
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: self-healing
            owner: prasanna
        spec:
          serviceAccountName: trust-check-sa
          containers:
          - name: trust-score
            image: ppankajs/self-healing-app:latest
            command: ["python", "/app/scripts/trust_score.py"]
          restartPolicy: OnFailure
