apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-scoring
  labels:
    app: self-healing
    owner: prasanna
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: self-healing
            owner: prasanna
        spec:
          containers:
          - name: health-score
            image: ppankajs/self-healing-app:latest
            command: ["python", "/app/scripts/health_scoring.py"]
          restartPolicy: OnFailure
