apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: self-healing
    owner: prasanna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-healing
      owner: prasanna
  template:
    metadata:
      labels:
        app: self-healing
        owner: prasanna
    spec:
      containers:
      - name: flask-container
        image: ppankajs/self-healing-app:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10