apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    - job_name: 'flask-app'
      metrics_path: /metrics
      static_configs:
        - targets: ['flask-service.default.svc.cluster.local:80']
