apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: score-storage
  labels:
    app: self-healing         
    owner: prasanna          
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
