apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollback-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollback-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollback-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: rollback-sa
  namespace: default
roleRef:
  kind: Role
  name: rollback-role
  apiGroup: rbac.authorization.k8s.io