apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: self-healing
    owner: prasanna
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: self-healing
    owner: prasanna
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
