apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredprobes
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredProbes
        listKind: K8sRequiredProbesList
        plural: k8srequiredprobes
        singular: k8srequiredprobes
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredprobes

        violation[{"msg": msg}] {
          not input.review.object.spec.template.spec.containers[_].livenessProbe
          msg := "Liveness probe is required"
        }

        violation[{"msg": msg}] {
          not input.review.object.spec.template.spec.containers[_].readinessProbe
          msg := "Readiness probe is required"
        }
